# Generated by Django 3.0.7 on 2020-08-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20200616_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome_url',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
    ]
