# Generated by Django 3.0.7 on 2020-08-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_nome_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome_url',
        ),
    ]
