# Generated by Django 3.0.7 on 2020-06-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='tamanho',
            field=models.CharField(default='x', max_length=2),
        ),
    ]
