# Generated by Django 3.0.7 on 2020-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_auto_20200625_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
