# Generated by Django 3.0.7 on 2020-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20200616_0850'),
        ('carrinho', '0003_itemcompra_finalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcompra',
            name='produto',
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='produto',
            field=models.ManyToManyField(null=True, to='loja.Produto'),
        ),
    ]
