# Generated by Django 3.0.7 on 2020-07-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20200616_0850'),
        ('carrinho', '0004_auto_20200701_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcompra',
            name='produto',
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='produto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.Produto'),
        ),
    ]
