# Generated by Django 3.0.7 on 2020-07-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0006_itemcompra_comprador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcompra',
            name='comprador',
        ),
    ]
