# Generated by Django 3.0.7 on 2020-07-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20200616_0850'),
        ('carrinho', '0007_remove_itemcompra_comprador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.Produto'),
        ),
    ]
