# Generated by Django 3.0.7 on 2020-07-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0010_compra_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
