# Generated by Django 3.0.7 on 2020-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0011_compra_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
