# Generated by Django 3.0.7 on 2020-07-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0012_auto_20200724_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
