# Generated by Django 3.0.7 on 2020-06-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.TextField(default=None),
        ),
    ]
