# Generated by Django 3.0.7 on 2020-06-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200630_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome',
            field=models.TextField(default=None, null=True),
        ),
    ]
