# Generated by Django 3.0.7 on 2020-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20200630_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
