# Generated by Django 3.0.7 on 2020-07-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0002_auto_20200716_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='cep',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='numeroCartao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='segurancaCartao',
            field=models.CharField(max_length=10),
        ),
    ]
