# Generated by Django 3.0.7 on 2020-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0004_auto_20200716_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='complemento',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
