# Generated by Django 3.0.7 on 2020-07-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0005_auto_20200716_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='transacao_id',
            field=models.CharField(default='x', max_length=15),
            preserve_default=False,
        ),
    ]
